### ISSUE TITLE
Login failing

### ISSUE THREAD

**Issue by Ecredes** [shuos-rst/ao3-bookmark-getter#1]
Hey thanks for developing this script, I've used it in the past from the original master branch. While trying to use your fork, I'm having trouble logging in now.  I noticed that ao3 has a 'accept terms and conditions' pop up on the initial visit to the login page, I'm wondering if that's what's causing the issue.  Do you know a work around?

**Comment by syrtis-m** [comment]
hi sorry for the late reply (more than a year 😬).

i've used this script after the update to have terms & conditions, so i don't think that's causing the issue. 

sorry i can't help :(
