### ISSUE TITLE
Noob / direction issues

### ISSUE THREAD

**Issue by hiaparker** [shuos-rst/ao3-bookmark-getter#2]
Hello this is my first real foray into python and while trying to use this scriipt i keep getting

PS C:\Users\the_v\Desktop\ao3\ao3-bookmark-getter-master> python ao3downloader.py helloiamparker
Traceback (most recent call last):
  File "C:\Users\the_v\Desktop\ao3\ao3-bookmark-getter-master\ao3downloader.py", line 6, in <module>
    import AO3
ModuleNotFoundError: No module named 'AO3'

errors. I tried to trouble shoot on my own and i know this may not be supported anymore but i was just hoping. I did download the ao3.api i noticed you had before but it didn't seem to help. Thank you.

**Comment by syrtis-m** [comment]
hi sorry for the super late response, i just saw this 😬

the package has to be installed through pip - here's a good intro to using pip: https://packaging.python.org/en/latest/tutorials/installing-packages/#requirements-for-installing-packages.

also note that the package name when installing through pip is `ao3_api` even though the import is `import AO3`

sorry for the late reply - if you have further issues, dm me on twitter: [@syrtis_](https://twitter.com/syrtis_)
